# Generated by Django 4.2.7 on 2023-12-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
