# Generated by Django 4.2.7 on 2023-12-07 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_remove_product_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'permissions': [('moderator', 'can change is_published, description, category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='changed_at',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='harvest',
            name='harvest_date',
            field=models.DateField(verbose_name='Дата начала использования'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Услуга'),
        ),
    ]
