# Generated by Django 4.2.7 on 2023-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_harvest_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'verbose_name': 'Регистрация', 'verbose_name_plural': 'Регистрации'},
        ),
        migrations.AddField(
            model_name='harvest',
            name='harvest_description',
            field=models.TextField(blank='True', null='True', verbose_name='Описание'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='harvest',
            name='harvest_date',
            field=models.DateField(verbose_name='Дата регистрации услуги'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Текущая регистрация (да/нет)'),
        ),
    ]
