# Generated by Django 5.0 on 2023-12-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_harvest_harvest_date_alter_harvest_is_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'permissions': [('moderator', 'can change is_published, description, category')], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
